// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.0 paddockPass.glb -T --shadows 
// Files: paddockPass.glb [425.88KB] > C:\Users\User\FormulaFan\client\public\models\f1PaddockPass\paddockPass-transformed.glb [54.66KB] (87%)
// */

// import React from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Model(props) {
//   const { nodes, materials } = useGLTF('/models/f1PaddockPass/paddockPass-transformed.glb')
//   return (
//     <group {...props} dispose={null}>
//       <mesh castShadow receiveShadow geometry={nodes.card.geometry} material={materials.base} />
//       <mesh castShadow receiveShadow geometry={nodes.clip.geometry} material={materials.metal} />
//     </group>
//   )
// }

// useGLTF.preload('/models/f1PaddockPass/paddockPass-transformed.glb')
